name: native_home_widgets
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.3.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_bloc: ^8.1.0
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  path_provider: ^2.0.10

dev_dependencies:
  hive_generator: ^1.1.0
  build_runner: ^2.2.0
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true
